### ISSUE TITLE
Hipster links

### ISSUE THREAD

**Issue by ShalokShalom** [emacs-themes/emacs-themes-site#11]
Link to source and MELPA is no more: https://emacsthemes.com/themes/hipster-theme.html

**Comment by caisah** [comment]
Thanks, I'll update accordingly. Looks like it's available here https://github.com/purcell/hipster-theme

**Comment by ShalokShalom** [comment]
thanks a lot
👍

**Comment by ShalokShalom** [comment]
See here: https://github.com/purcell/hipster-theme/pull/1

**Comment by caisah** [comment]
@ShalokShalom If you decide on maintaining the theme please ping me and I will change the details.
